### ISSUE TITLE
Move this repo to JuliaWeb

### ISSUE THREAD

**Issue by aviks** [JuliaLang/juliawebstack.org#11]
Shouldn't this repo be within the JuliaWeb organisation?

@StefanKarpinski  You are admin on both teams, so best if you do it. 

@astrieanna How is this hosted? GH-pages? Does that need to change? 

cc: @IainNZ

**Comment by sbromberger** [comment]
+1. I didn't even know this existed until today :)

**Comment by ivarne** [comment]
+1 (Bump!)

**Comment by astrieanna** [comment]
I'm pretty sure it's hosted on github pages. The Makefile probably needs to be updated (since this and the packages have moved organizations on github), and the URL would need to be updated to point to this repo's new github pages url. I believe @danielmendel controls the url last time I heard?

**Comment by tkelman** [comment]
@malmaud could you give me admin access to JuliaWeb and/or JuliaArchive? Most of these packages are deprecated and have been moved to the latter.

**Comment by IainNZ** [comment]
I just gave you both
