### ISSUE TITLE
Add Links to Github

### ISSUE THREAD

**Issue by astrieanna** [JuliaLang/juliawebstack.org#4]
I couldn't find any links on the webpage to the actual repos. Considering that there's not enough documentation that you aren't just going to have to look at the source, there really need to be links (as opposed to everyone googling "Morsel.jl", etc).

**Comment by EricForgy** [comment]
I agree.

**Comment by jiahao** [comment]
A pull request would be most welcome.

**Comment by EricForgy** [comment]
What is a pull request? :) I'll try

**Comment by EricForgy** [comment]
Hi jiahao. By the way, I really did need to google "pull request" :)

I've submitted one now. Hope its alright.
